# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop lib

test:
	OCAMLRUNPARAM=b dune exec test/test.exe

play:
	OCAMLRUNPARAM=b dune exec bin/main.exe

check:
	@bash check.sh

finalcheck:
	@bash check.sh final

zip:
	rm -f poker.zip
	zip -r poker.zip . -x@exclude.lst

clean:
	dune clean
	rm -f cards.zip

doc:
	dune build @doc

opendoc: doc
	@bash opendoc.sh
